### ISSUE TITLE
When libraries are loaded into your script, make sure that you check  that the library is installed

### ISSUE THREAD

**Issue by molikd** [pfrender-laboratory/N-Most-Diverse-Sequences#1]
When libraries are loaded into your script, first check  that the library is installed, and if it is not, install it. 

ie:
```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install()
```

**Comment by michalekb** [comment]
- The code works when I remove a package and then run those line in the console
- When I run the script in terminal, however, I get this error:
Error in contrib.url(repos, "source") : 
  trying to use CRAN without setting a mirror
Calls: install.packages -> contrib.url
Execution halted

**Comment by molikd** [comment]
install.packages('package', repos='https://cloud.r-project.org')
