### ISSUE TITLE
while loop of diversity methods when n=1 gives error

### ISSUE THREAD

**Issue by michalekb** [pfrender-laboratory/N-Most-Diverse-Sequences#5]
When n=1, while loop line gives the error:

"Error in while (nrow(final_set) > n) { : argument is of length zero
Execution halted"

- not a problem of assigning a value into n, must be something to do with the nrow(final_set) part? Can't figure it out.

**Comment by molikd** [comment]
What is the output of the following:
```
 if(!is.null(nrow(final_set)) & (nrow(final_set) > n)){
     #do stuff
 }
```

**Comment by michalekb** [comment]
It gives the exact same error.

**Comment by molikd** [comment]
okay, output everything every step through the while loop.
